FROM ubuntu:20.04

RUN \
    apt-get -y update && \
    apt-get -y install \
        qemu=1:4.2-3ubuntu6.15 \
        qemu-utils=1:4.2-3ubuntu6.15 \
        qemu-system-x86=1:4.2-3ubuntu6.15 \
        telnet=0.17-41.2build1 \
        wget=1.20.3-1ubuntu1

